#!/bin/sh

# TODO: use AUTOPKGTEST_TMP
testdir='/tmp/sqlite_fdw_test'
rm -rf "$testdir"
mkdir "$testdir"
cp -a sql/init_data/*.data "$testdir"

sqlite3 "$testdir/post.db" < sql/init_data/init_post.sql;
sqlite3 "$testdir/core.db" < sql/init_data/init_core.sql;
sqlite3 "$testdir/common.db" < sql/init_data/init.sql;
sqlite3 "$testdir/selectfunc.db" < sql/init_data/init_selectfunc.sql;

pg_buildext -m REGRESS_PREFIX=17.0 installcheck

